using OpenRename;
var root = Path.Combine(Path.GetTempPath(), "openrename-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(root); var a = Path.Combine(root, "draft-one.txt"); var b = Path.Combine(root, "draft-two.txt"); File.WriteAllText(a, "a"); File.WriteAllText(b, "b"); var plan = RenameEngine.Preview(new[] { a, b }, "draft", "final"); if (plan.Count != 2 || !Path.GetFileName(plan[0].ProposedPath).StartsWith("final")) throw new Exception("Preview failed."); RenameEngine.Execute(plan); if (!File.Exists(Path.Combine(root, "final-one.txt"))) throw new Exception("Execution failed."); RenameEngine.Execute(plan.Select(x => new RenameItem(x.ProposedPath, x.OriginalPath))); if (!File.Exists(a)) throw new Exception("Undo failed."); Directory.Delete(root, true); Console.WriteLine("PASS: rename preview, execution, and undo");
var conflictRoot = Path.Combine(Path.GetTempPath(), "openrename-conflict-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(conflictRoot); var c1 = Path.Combine(conflictRoot, "one.txt"); var c2 = Path.Combine(conflictRoot, "two.txt"); File.WriteAllText(c1, "1"); File.WriteAllText(c2, "2"); var conflict = new[] { new RenameItem(c1, Path.Combine(conflictRoot, "same.txt")), new RenameItem(c2, Path.Combine(conflictRoot, "same.txt")) }; try { RenameEngine.Validate(conflict); throw new Exception("Duplicate destination was not rejected."); } catch (InvalidOperationException) { } if (!File.Exists(c1) || !File.Exists(c2)) throw new Exception("Conflict validation changed files."); Directory.Delete(conflictRoot, true); Console.WriteLine("PASS: duplicate destination protection");

var swapRoot = Path.Combine(Path.GetTempPath(), "openrename-swap-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(swapRoot); var left = Path.Combine(swapRoot, "left.txt"); var right = Path.Combine(swapRoot, "right.txt"); File.WriteAllText(left, "LEFT"); File.WriteAllText(right, "RIGHT");
RenameEngine.Execute(new[] { new RenameItem(left, right), new RenameItem(right, left) });
if (File.ReadAllText(left) != "RIGHT" || File.ReadAllText(right) != "LEFT") throw new Exception("Transactional swap failed.");
if (Directory.EnumerateFiles(swapRoot, ".openrename-*.tmp").Any()) throw new Exception("Temporary rename files were left behind.");
try { RenameEngine.Preview(new[] { left }, "", "x"); throw new Exception("Empty find text was accepted."); } catch (ArgumentException) { }
Directory.Delete(swapRoot, true); Console.WriteLine("PASS: transactional swaps and temporary-file cleanup");
